package com.openclassrooms.ycyw.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;


/**
 * Entity representing a support request submitted by a user.
 * <p>
 * This entity is linked to a {@link UserEntity}, who initiates the request.
 * Each request contains a subject, a status, and a timestamp indicating when it was sent.
 * </p>
*/
@Entity
@Getter
@SuperBuilder(toBuilder = true)
@Table(name = "support_requests")
@NoArgsConstructor
public class SupportRequestEntity extends Auditable {
    

    /**
     * Unique identifier for the support request.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Subject or title of the support request.
     * Cannot be null.
     */
    @Column(nullable = false, length = 100)
    private String subject;

     /**
     * Content of the support request.
     * Cannot be null.
     */
    @Column(nullable = false, length = 2500)
    private String content;

    /**
     * Current status of the support request.
     * Can be OPEN, PROGRESS, or CLOSED.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private SupportRequestStatus status;

    /**
     * Date and time when the request was initially submitted.
     */
    @Column(name = "sent_at", nullable = false)
    private java.time.Instant sentAt;

    /**
     * The user who submitted the request.
     * Each support request is associated with a single user.
     */
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private UserEntity user;
}
